name: Browser Extension CD

on:
  push:
    tags:
       - 'v*'

jobs:
  build:
    name: Publish browser-extension
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Build
      run: |
        npm ci
        npm run build

    - name: Upload & release
      uses: mnao305/chrome-extension-upload@1.1.1
      with:
        file-path: dist/*.zip
        extension-id: hogefuga(extension id)
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}
        glob: true
